apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app
rules:
  - apiGroups:
      - "*"
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-custom-role-binding
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: app
